### ISSUE TITLE
GulpSSHDeploy is not a constructor

### ISSUE THREAD

**Issue by ranvirgorai** [jwir3/gulp-ssh-deploy#12]
I am trying to do this .
let deployer = new GulpSSHDeploy(options, gulp);

**Comment by valentincvetkovskiottoboni** [comment]
Me to and I am getting the same result: GulpSSHDeploy is not a constructor!

**Comment by StijnRuts** [comment]
I had the same. You should use it like this:
```
var ssh_deploy = require('gulp-ssh-deploy');
let deployer = new ssh_deploy.GulpSSHDeploy(options, gulp);
```

**Comment by jwir3** [comment]
Yep, my bad. I'll make sure the README is updated to account for this.

Also, I'm so sorry it took me so long to see this. I don't know exactly why, but I wasn't receiving notifications for this repo.
